from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowAdmin(QtWidgets.QMainWindow):
    def setupUi(self, WindowAdmin):
        WindowAdmin.setObjectName("WindowAdmin")
        WindowAdmin.resize(1195, 860)
        self.centralwidget = QtWidgets.QWidget(WindowAdmin)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(30, 250, 1151, 551))
        self.tableView.setObjectName("tableView")
        self.pushButton_dov = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dov.setGeometry(QtCore.QRect(30, 200, 111, 31))
        self.pushButton_dov.setObjectName("pushButton_dov")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(190, 200, 101, 31))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 59, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 59, 18))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 113, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 80, 113, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 130, 113, 26))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 200, 101, 31))
        self.pushButton.setObjectName("pushButton")
        WindowAdmin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(WindowAdmin)
        self.statusbar.setObjectName("statusbar")
        WindowAdmin.setStatusBar(self.statusbar)

        self.retranslateUi(WindowAdmin)
        QtCore.QMetaObject.connectSlotsByName(WindowAdmin)

    def retranslateUi(self, WindowAdmin):
        _translate = QtCore.QCoreApplication.translate
        WindowAdmin.setWindowTitle(_translate("WindowAdmin", "Администратор "))
        self.pushButton_dov.setText(_translate("WindowAdmin", "Добавить "))
        self.pushButton_delete.setText(_translate("WindowAdmin", "Удалить"))
        self.label.setText(_translate("WindowAdmin", "Имя"))
        self.label_2.setText(_translate("WindowAdmin", "Фамилия"))
        self.label_3.setText(_translate("WindowAdmin", "Отчество "))
        self.pushButton.setText(_translate("WindowAdmin", "Обновить"))
